### PR TITLE
(fix) and to or 

### PR DESCRIPTION
**Pull request by gmach**
merged comment and added new comment
changed and to or

Some tests done 1 2 3..
To test run with argument Xyz

### CODE REVIEW

**Comment by glamdee** [comment]
> merged comment and added new comment changed and to or
> 
> Some tests done 1 2 3.. To test run with argument Xyz

**Review by glamdee — COMMENTED** [review]
Nice fix but can you keep it on one line thanks

**Review by glamdee — CHANGES_REQUESTED** [review]
keep one line

**Comment by gmach** [comment]
ok I have kept one single line now

**Review by glamdee — APPROVED** [review]
excellent you are good to go

**Comment by glamdee** [comment]
merged gmachs fix

**Pull request merged**
